// source: airchat/gateway/v2/activity_stream_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var airchat_activity_v2_activity_pb = require('../../../airchat/activity/v2/activity_pb.js');
goog.object.extend(proto, airchat_activity_v2_activity_pb);
goog.exportSymbol('proto.airchat.gateway.v2.ActivityStreamPingRequest', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.ActivityStreamRequest', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.ActivityStreamRequest.RequestCase', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.ActivityStreamResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.ActivityStreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.airchat.gateway.v2.ActivityStreamRequest.oneofGroups_);
};
goog.inherits(proto.airchat.gateway.v2.ActivityStreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.ActivityStreamRequest.displayName = 'proto.airchat.gateway.v2.ActivityStreamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.ActivityStreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airchat.gateway.v2.ActivityStreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.ActivityStreamResponse.displayName = 'proto.airchat.gateway.v2.ActivityStreamResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airchat.gateway.v2.ActivityStreamPingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.ActivityStreamPingRequest.displayName = 'proto.airchat.gateway.v2.ActivityStreamPingRequest';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.airchat.gateway.v2.ActivityStreamRequest.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  PING: 1
};

/**
 * @return {proto.airchat.gateway.v2.ActivityStreamRequest.RequestCase}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.getRequestCase = function() {
  return /** @type {proto.airchat.gateway.v2.ActivityStreamRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.airchat.gateway.v2.ActivityStreamRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.ActivityStreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.ActivityStreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ping: (f = msg.getPing()) && proto.airchat.gateway.v2.ActivityStreamPingRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.ActivityStreamRequest}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.ActivityStreamRequest;
  return proto.airchat.gateway.v2.ActivityStreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.ActivityStreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.ActivityStreamRequest}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.airchat.gateway.v2.ActivityStreamPingRequest;
      reader.readMessage(value,proto.airchat.gateway.v2.ActivityStreamPingRequest.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.ActivityStreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.ActivityStreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.airchat.gateway.v2.ActivityStreamPingRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional ActivityStreamPingRequest ping = 1;
 * @return {?proto.airchat.gateway.v2.ActivityStreamPingRequest}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.getPing = function() {
  return /** @type{?proto.airchat.gateway.v2.ActivityStreamPingRequest} */ (
    jspb.Message.getWrapperField(this, proto.airchat.gateway.v2.ActivityStreamPingRequest, 1));
};


/**
 * @param {?proto.airchat.gateway.v2.ActivityStreamPingRequest|undefined} value
 * @return {!proto.airchat.gateway.v2.ActivityStreamRequest} returns this
*/
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.setPing = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.airchat.gateway.v2.ActivityStreamRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airchat.gateway.v2.ActivityStreamRequest} returns this
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.clearPing = function() {
  return this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airchat.gateway.v2.ActivityStreamRequest.prototype.hasPing = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.ActivityStreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.ActivityStreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    logItem: (f = msg.getLogItem()) && airchat_activity_v2_activity_pb.ActivityLogItem.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.ActivityStreamResponse}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.ActivityStreamResponse;
  return proto.airchat.gateway.v2.ActivityStreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.ActivityStreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.ActivityStreamResponse}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new airchat_activity_v2_activity_pb.ActivityLogItem;
      reader.readMessage(value,airchat_activity_v2_activity_pb.ActivityLogItem.deserializeBinaryFromReader);
      msg.setLogItem(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.ActivityStreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.ActivityStreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLogItem();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      airchat_activity_v2_activity_pb.ActivityLogItem.serializeBinaryToWriter
    );
  }
};


/**
 * optional airchat.activity.v2.ActivityLogItem log_item = 1;
 * @return {?proto.airchat.activity.v2.ActivityLogItem}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.getLogItem = function() {
  return /** @type{?proto.airchat.activity.v2.ActivityLogItem} */ (
    jspb.Message.getWrapperField(this, airchat_activity_v2_activity_pb.ActivityLogItem, 1));
};


/**
 * @param {?proto.airchat.activity.v2.ActivityLogItem|undefined} value
 * @return {!proto.airchat.gateway.v2.ActivityStreamResponse} returns this
*/
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.setLogItem = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airchat.gateway.v2.ActivityStreamResponse} returns this
 */
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.clearLogItem = function() {
  return this.setLogItem(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airchat.gateway.v2.ActivityStreamResponse.prototype.hasLogItem = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.ActivityStreamPingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.ActivityStreamPingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.ActivityStreamPingRequest}
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.ActivityStreamPingRequest;
  return proto.airchat.gateway.v2.ActivityStreamPingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.ActivityStreamPingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.ActivityStreamPingRequest}
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.ActivityStreamPingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.ActivityStreamPingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.ActivityStreamPingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.airchat.gateway.v2);
