// source: airchat/gateway/v2/notification_stream_api.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = (function() {
  if (this) { return this; }
  if (typeof window !== 'undefined') { return window; }
  if (typeof global !== 'undefined') { return global; }
  if (typeof self !== 'undefined') { return self; }
  return Function('return this')();
}.call(null));

var airchat_gateway_v2_notification_stream_pb = require('../../../airchat/gateway/v2/notification_stream_pb.js');
goog.object.extend(proto, airchat_gateway_v2_notification_stream_pb);
goog.exportSymbol('proto.airchat.gateway.v2.NotificationStreamRequest', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.NotificationStreamRequest.RequestCase', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.NotificationStreamResponse', null, global);
goog.exportSymbol('proto.airchat.gateway.v2.PingRequest', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.NotificationStreamRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, proto.airchat.gateway.v2.NotificationStreamRequest.oneofGroups_);
};
goog.inherits(proto.airchat.gateway.v2.NotificationStreamRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.NotificationStreamRequest.displayName = 'proto.airchat.gateway.v2.NotificationStreamRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.NotificationStreamResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airchat.gateway.v2.NotificationStreamResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.NotificationStreamResponse.displayName = 'proto.airchat.gateway.v2.NotificationStreamResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.airchat.gateway.v2.PingRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.airchat.gateway.v2.PingRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.airchat.gateway.v2.PingRequest.displayName = 'proto.airchat.gateway.v2.PingRequest';
}

/**
 * Oneof group definitions for this message. Each group defines the field
 * numbers belonging to that group. When of these fields' value is set, all
 * other fields in the group are cleared. During deserialization, if multiple
 * fields are encountered for a group, only the last value seen will be kept.
 * @private {!Array<!Array<number>>}
 * @const
 */
proto.airchat.gateway.v2.NotificationStreamRequest.oneofGroups_ = [[1]];

/**
 * @enum {number}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.RequestCase = {
  REQUEST_NOT_SET: 0,
  PING: 1
};

/**
 * @return {proto.airchat.gateway.v2.NotificationStreamRequest.RequestCase}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.getRequestCase = function() {
  return /** @type {proto.airchat.gateway.v2.NotificationStreamRequest.RequestCase} */(jspb.Message.computeOneofCase(this, proto.airchat.gateway.v2.NotificationStreamRequest.oneofGroups_[0]));
};



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.NotificationStreamRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.NotificationStreamRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.NotificationStreamRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    ping: (f = msg.getPing()) && proto.airchat.gateway.v2.PingRequest.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.NotificationStreamRequest}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.NotificationStreamRequest;
  return proto.airchat.gateway.v2.NotificationStreamRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.NotificationStreamRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.NotificationStreamRequest}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.airchat.gateway.v2.PingRequest;
      reader.readMessage(value,proto.airchat.gateway.v2.PingRequest.deserializeBinaryFromReader);
      msg.setPing(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.NotificationStreamRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.NotificationStreamRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.NotificationStreamRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPing();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.airchat.gateway.v2.PingRequest.serializeBinaryToWriter
    );
  }
};


/**
 * optional PingRequest ping = 1;
 * @return {?proto.airchat.gateway.v2.PingRequest}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.getPing = function() {
  return /** @type{?proto.airchat.gateway.v2.PingRequest} */ (
    jspb.Message.getWrapperField(this, proto.airchat.gateway.v2.PingRequest, 1));
};


/**
 * @param {?proto.airchat.gateway.v2.PingRequest|undefined} value
 * @return {!proto.airchat.gateway.v2.NotificationStreamRequest} returns this
*/
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.setPing = function(value) {
  return jspb.Message.setOneofWrapperField(this, 1, proto.airchat.gateway.v2.NotificationStreamRequest.oneofGroups_[0], value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airchat.gateway.v2.NotificationStreamRequest} returns this
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.clearPing = function() {
  return this.setPing(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airchat.gateway.v2.NotificationStreamRequest.prototype.hasPing = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.NotificationStreamResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.NotificationStreamResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.NotificationStreamResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    envelope: (f = msg.getEnvelope()) && airchat_gateway_v2_notification_stream_pb.Envelope.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.NotificationStreamResponse}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.NotificationStreamResponse;
  return proto.airchat.gateway.v2.NotificationStreamResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.NotificationStreamResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.NotificationStreamResponse}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new airchat_gateway_v2_notification_stream_pb.Envelope;
      reader.readMessage(value,airchat_gateway_v2_notification_stream_pb.Envelope.deserializeBinaryFromReader);
      msg.setEnvelope(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.NotificationStreamResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.NotificationStreamResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.NotificationStreamResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEnvelope();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      airchat_gateway_v2_notification_stream_pb.Envelope.serializeBinaryToWriter
    );
  }
};


/**
 * optional Envelope envelope = 1;
 * @return {?proto.airchat.gateway.v2.Envelope}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.getEnvelope = function() {
  return /** @type{?proto.airchat.gateway.v2.Envelope} */ (
    jspb.Message.getWrapperField(this, airchat_gateway_v2_notification_stream_pb.Envelope, 1));
};


/**
 * @param {?proto.airchat.gateway.v2.Envelope|undefined} value
 * @return {!proto.airchat.gateway.v2.NotificationStreamResponse} returns this
*/
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.setEnvelope = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.airchat.gateway.v2.NotificationStreamResponse} returns this
 */
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.clearEnvelope = function() {
  return this.setEnvelope(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.airchat.gateway.v2.NotificationStreamResponse.prototype.hasEnvelope = function() {
  return jspb.Message.getField(this, 1) != null;
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.airchat.gateway.v2.PingRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.airchat.gateway.v2.PingRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.airchat.gateway.v2.PingRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.PingRequest.toObject = function(includeInstance, msg) {
  var f, obj = {

  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.airchat.gateway.v2.PingRequest}
 */
proto.airchat.gateway.v2.PingRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.airchat.gateway.v2.PingRequest;
  return proto.airchat.gateway.v2.PingRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.airchat.gateway.v2.PingRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.airchat.gateway.v2.PingRequest}
 */
proto.airchat.gateway.v2.PingRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.airchat.gateway.v2.PingRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.airchat.gateway.v2.PingRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.airchat.gateway.v2.PingRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.airchat.gateway.v2.PingRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
};


goog.object.extend(exports, proto.airchat.gateway.v2);
