/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/Osb4fXnt7oL
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
export function FAQ() {
  return (
    <div className="max-w-3xl mx-auto py-12 px-4 sm:px-6 lg:py-16 lg:px-8">
      <div className="text-center">
        <h2 className="text-3xl font-extrabold tracking-tight text-gray-900 dark:text-gray-100 sm:text-4xl">
          Frequently Asked Questions
        </h2>
        <p className="mt-4 text-lg text-gray-500 dark:text-gray-400">Got a question? We have got answers.</p>
      </div>
      <div className="mt-12 space-y-8">
        <div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">What is your refund policy?</h3>
          <p className="mt-2 text-base text-gray-500 dark:text-gray-400">
            We offer a 30-day money-back guarantee on all of our products. If you are not satisfied with your purchase,
            you can return it for a full refund within 30 days of the original purchase date.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">How do I contact customer support?</h3>
          <p className="mt-2 text-base text-gray-500 dark:text-gray-400">
            You can reach our customer support team by email at support@example.com or by phone at 1-800-555-1234. We are
            available Monday through Friday, 9am to 5pm EST.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">
            Do you offer any discounts or promotions?
          </h3>
          <p className="mt-2 text-base text-gray-500 dark:text-gray-400">
            Yes, we offer a variety of discounts and promotions throughout the year. You can check our website or sign
            up for our newsletter to stay up-to-date on our latest offers.
          </p>
        </div>
        <div>
          <h3 className="text-lg font-bold text-gray-900 dark:text-gray-100">How long does shipping take?</h3>
          <p className="mt-2 text-base text-gray-500 dark:text-gray-400">
            Shipping times can vary depending on your location and the shipping method you choose. Standard shipping
            typically takes 5-7 business days, while expedited shipping can be as fast as 1-2 business days.
          </p>
        </div>
      </div>
    </div>
  )
}
